baseurl: "https://example.org/"
title: "Gophercon EU"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Gophercon EU"
  Description: "Conference description"
  Date: "30.05-01.06.2019"
  Venue: "Hard Rock Hotel"
  Address: ""
  City:  "Tenerife"
  State: "Spain"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"


  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - schedule
    - location
    - speakers
    - mc
    - contact

  # Titles which you can translate to other languages
  Titles:
    schedule: "Schedule"
    location: "Location"
    speakers: "Speakers"
    mc: "MC"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Workshops"
      time: "30.05"

    - name: "Talks track 1"
      time: "31.05"

    - name: "Talks track 2"
      time: "31.05"

    - name: "Community day"
      time: "01.06"

